name: Auto message for Pull Requests and Issue
on: [pull_request, issues]
jobs:
  build: 
    name: Hello new contributor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.WORKFLOW_TOKEN }}
          issues-message: " Thanks!!🙂 for creating an issue. Please describe your issue. And head on to `Discussion` tab to discuss about it."
          pr-message: "Hello👋 Contributor, thanks for making a pull request.<br>It will be reviewed by the maintainers soon.<br>You can ask any doubts here under the pull request or ask it in `Discussions` section. Please follow the `CONTRIBUTIONS GUIDLINES` which you can find `README.md` file of each folder. <br>Till then keep contributing. <br>Happy Coding🙂"
